# Generated by Django 3.0.4 on 2020-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemp',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='female',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='male',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='other',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='pancard',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addemp',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
